spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?useSSL=false
    username: root
    password: Vitalex88
  jpa:
    hibernate:
      ddl-auto: update

someParameter:
  value: "1_000_000"